post/urls.py
from django.urls import path 
from . import views 

app_name='post'

urlpatterns = [
	path('', views.post_list, name='post_list'),
	path('<slug:category_slug>', views.post_list, name='post_list_by_category'),
	path('<int:id>/<slug:slug>/', views.post_detail, name='post_detail'),
	path('search/', views.seacrch_post, name='search'),
	path('like/<int:id_post>/', views.like_post, name='like'),
	path('like_post_list/<int:id_post>/', views.like_post_list, name='like_post_list'),
	path('comment/<int:id>/', views.add_comment_to_post, name='add_comment_to_post'),
]

test_site/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

from . import views 

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('post.urls')),
]

urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static( settings.STATIC_URL, document_root = settings.STATIC_ROOT )

user/urls.py
from django.urls import path 

from django_registration.backends.activation.views import RegistrationView

from . import views 
from .models import User
from .forms import CustomUserForm
app_name='user'

urlpatterns = [
	path('register/', RegistrationView.as_view(form_class=CustomUserForm), name='registration_register'),
]

post/models.py
from datetime import timezone

from django.db import models
from django.conf import settings

from django.urls import reverse 

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)

	class Meta:
		ordering = ('name', )

	def get_absolute_url(self):
		return reverse('post:post_list_by_category', args=[self.slug])

	def __str__(self):
		return self.name 

class Post(models.Model):
	category = models.ForeignKey(Category, related_name='posts', on_delete=models.SET_NULL, null=True)
	title = models.CharField(max_length=120, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True, blank=True)
	body = models.TextField()
	image = models.ImageField(upload_to='img_post')


	

	class Meta:
		ordering = ('title', )
		index_together = (('id', 'slug'),)
		
	def get_absolute_url(self):
		return reverse('post:post_detail', args=[self.id, self.slug])


	def __str__(self):
		return self.title 

class Comment(models.Model):
	post = models.ForeignKey('post.Post', on_delete=models.CASCADE, related_name='comments')
	author = models.ForeignKey('user.User', on_delete=models.CASCADE )
	text = models.TextField()

	def __str__(self):
		return self.text


class Like(models.Model):
	user = models.ForeignKey('user.User', on_delete=models.CASCADE, null=True)
	post = models.ForeignKey('post.Post', on_delete=models.CASCADE)
	creation_date = models.DateTimeField(auto_now=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(unique=True, null=True)
	username = models.CharField(max_length=200)
	is_staff = models.BooleanField(
		_('staff status'),
		default=False,
		help_text=_('Designates whether the user can log into this admin site.'),
		)
	is_active = models.BooleanField(
		_('active'),
		default=True,
		help_text=_(
			'Designates whether this user should be treated as active. ''Unselect this instead of deleting accounts.'
			),
		)

	USERNAME_FIELD = 'email'
	objects = CustomUserManager()
	birthday = models.DateField(auto_now_add=False, blank=True, null=True)
	country = models.CharField(max_length=120, blank=True, null=True)
	city = models.CharField(max_length=120, blank=True, null=True)

	def email_user(self, subject, message, from_email=None, **kwargs):

		send_mail(subject, message, from_email, [self.email], **kwargs)

post/forms.py
from django import forms 


class SearchForm( forms.Form ):
	body = forms.CharField(max_length=120, label='')


class CommentForm( forms.Form ):
	body = forms.CharField(max_length=240, label='')

user/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django_registration.forms import RegistrationForm ,RegistrationFormUniqueEmail

from .models import User 


class CustomUserForm(RegistrationFormUniqueEmail):

	class Meta():
		model = User
		fields = ('username', 'email', 'password1', 'password2', 'country', 'city', 'birthday')

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator 
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST 

from .models import Category, Post,  Comment, Like
from .forms import SearchForm, CommentForm

from user.models import User
# Create your views here.

@login_required()
def post_list(request, category_slug=None):
	category = None 
	categories = Category.objects.all()
	posts = Post.objects.all()
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		posts = posts.filter(category=category)

	paginator = Paginator(posts, 3)
	page_number = request.GET.get('page', 1)
	page = paginator.get_page(page_number)

	if page.has_previous():
		prev_url = '?page={}'.format(page.previous_page_number())
	else:
		prev_url = ''

	if page.has_next():
		next_url = '?page={}'.format(page.next_page_number())
	else:
		next_url = ''

	search = SearchForm()
	like = Like.objects.all()

	for post in page.object_list:
		post.likes = post.like_set.all().count()
	context = {'category': category, 
	'categories': categories, 
	'page_object': page,
	'next_url': next_url,
	'prev_url': prev_url,
	'search':search,
	'like': like
	}

	return render( request, 'posts/list.html', context)

@login_required()
def post_detail(request,id, slug ):
	post = get_object_or_404(Post, id=id, slug=slug)
	search = SearchForm()
	comment_form = CommentForm()
	comments = Comment.objects.filter(post=post)

	paginator = Paginator(comments, 3)
	page_number = request.GET.get('page', 1)
	page = paginator.get_page(page_number)

	if page.has_previous():
		prev_url = '?page={}'.format(page.previous_page_number())
	else:
		prev_url = ''

	if page.has_next():
		next_url = '?page={}'.format(page.next_page_number())
	else:
		next_url = ''
	number_of_likes = post.like_set.all().count()

	context = {
		'post': post,
		'page_object': page,
		'next_url': next_url,
		'prev_url': prev_url,
		'search': search,
		'comment_form': comment_form ,
		'comments': comments,
		'count': number_of_likes
	}
	return render(request, 'posts/detail.html', context=context)



@require_POST
def like_post(request, id_post):
	post = get_object_or_404(Post, id = id_post)
	user = get_object_or_404(User, email=request.user)

	new_like, created = Like.objects.get_or_create(user=user, post=post)
	if not created:
		Like.objects.get(user=new_like.user, post=post).delete()
	

	return redirect('post:post_detail', str(post.id), post.slug)


@require_POST
def like_post_list(request, id_post):
	post = get_object_or_404(Post, id = id_post)
	user = get_object_or_404(User, email=request.user)

	new_like, created = Like.objects.get_or_create(user=user, post=post)
	if not created:
		Like.objects.get(user=new_like.user, post=post).delete()
	
		
	return redirect('post:post_list')

@require_POST
def seacrch_post(request):
	form = SearchForm( request.POST )

	if form.is_valid():
		search = form.cleaned_data['body']
		try:
			post = Post.objects.get(title=search) 
			return redirect('post:post_detail', post.id, post.slug)
		except:
			return redirect('post:post_list')
	else:
		return redirect('post:post_list')

@require_POST
def add_comment_to_post(request, id):
    post = get_object_or_404(Post, id=id)
    user = get_object_or_404(User, email=request.user)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            Comment.objects.create(post = post, author = user, text = form.cleaned_data['body'])
            return redirect('post:post_detail', str(post.id), post.slug)
    else:
        form = CommentForm()
    return render(request, 'post/add_comment_to_post.html', {'form': form})

	

test_site/views.py
from django.shortcuts import  redirect


def index(request):
    return redirect('post:post_list')

user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Web tests - {% block title %} {% endblock title %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		{% if user.is_authenticated %}
		<a class="navbar-brand" href="{% url 'post:post_list' %}">Test site</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'post:post_list' %}">Go to posts <span class="sr-only">(current)</span></a>
				</li>

				<li class="nav-item">
					{% block search %}
					 {% endblock %}
				</li>
			</ul>
			{% endif %}
			{% if user.is_authenticated %}
				<a class="btn btn-success mr-2 " href="{% url 'logout' %}" role="button">Log out</a>
			{% else %}
			<form class="form-inline my-2 my-lg-0">
				<a class="btn btn-success mr-2 " href="{% url 'user:registration_register' %}" role="button">Registration</a>
				<a class="btn btn-primary" href="{% url 'login' %}" role="button">Log in</a>
			</form>
			{% endif %}
		</div>
	</nav>
	{% block content %}
		
	{% endblock %}
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/django_registration/activation_complete.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center">
	<h1>Активация</h1>

Ваша учетная запись активирована. <a href="{% url 'post:post_list' %}">Заходите</a> на сайт.
<br/><br/>
</div>
{% endblock %}

templates/django_registration/logout.html
{% extends "base.html"  %}
{% block content %}
<div class="container">
	<h1>Выход</h1>
Спасибо, что были с нами. Ждем вас снова.<br/><br/>
</div>

{% endblock %}

templates/django_registration/registration_complete.html
{% extends "base.html"  %}
{% block content %}
<div class="container text-center">
<h1>Регистрация завершена</h1>
<p>Спасибо за уделённое время. На ваш e-mail отправлен 
код подтверждения. Необходимо подтвердить регистрацию, 
просто кликнув по указанной ссылке.</p><br/><br/>

</div>
{% endblock %}

templates/django_registration/registration_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  

  <h2>Sign up</h2>

  <form method="post">
  
      {% for field in form %}
      <p>
        {{ field|as_crispy_field }}

      </p>
      {% endfor %}
      {% csrf_token %}
    <button type="submit" class='btn btn-primary'>Sign up</button>
  </form>
  </div>
{% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
	Detail post
{% endblock %}

{% block search %}
<form class="form-inline my-2 my-lg-0" action="{% url 'post:search' %}" method="POST">
	{% csrf_token %}
	{{ search.body |as_crispy_field }}

<input type="submit" class='btn btn-success ml-1' value="Search"></div>
</form>
{% endblock %}

{% block content %}

<div class="row m-2">
	<div class="col-6">
		<img src="{{ MEDIA_ROOT }}{{ post.image.url }}" alt="" class ='img-thumbnail'>
	</div>
	<div class="col-6">

		<h1>{{ post.title }}</h1>
		<p>{{post.body}}</p>
		<p>{{count}}</p>
		<form action="{% url 'post:like' post.id %}" method="post">
			<div class="row">
				<div class="col"> 
					<input type="submit" class='btn btn-success' value="Like"></div>
				</div>
				{% csrf_token %}
			</form>

		<form action="{% url 'post:add_comment_to_post' post.id %}" method="post">
			<div class="row">
	{% csrf_token %}
	{{ comment_form.body |as_crispy_field }}
				{% csrf_token %}
				<input type="submit" class='btn btn-success ml-1' value="Add comment">
		</form>
		<hr>
</div>

		{% for comment in page_object.object_list  %}
			<div class="row">
				<div class="col">
					<p class="h4">{{comment.author.username}}</p>
					<p>{{comment.text}}</p>
				</div>
			</div>
		{% endfor %}
		<nav aria-label="..." class='d-flex justify-content-center m-2'>
      <ul class="pagination">
        <li class="page-item {% if  not prev_url%} disabled {% endif %}">
          <a class="page-link" href="{{prev_url}}" tabindex="-1">Previous</a>
        </li>
        {% for n in page_object.paginator.page_range  %}
        {% if page_object.number == n %} 
        <li class="page-item active">
          <a class="page-link" href="?page={{n}}">{{ n }}</a>
        </li>
        {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
        <li class="page-item ">
          <a class="page-link" href="?page={{n}}">{{ n }}</a>
        </li>

        {% endif %}

        {% endfor %}
        <li class="page-item {% if  not next_url%} disabled {% endif %}">
          <a class="page-link" href="{{next_url}}" tabindex="-1">Next</a>
        </li>

      </ul>
    </nav>
{% endblock content %}

templates/posts/list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
	List posts
{% endblock %}
{% block search %}
<form class="form-inline my-2 my-lg-0" action="{% url 'post:search' %}" method="POST">
	{% csrf_token %}
{{ search.body |as_crispy_field}}

<input type="submit" class='btn btn-success ml-1' value="Search"></div>
</form>
{% endblock %}

{% block content %}
	<h1 class="h2 text-center">{% if category %}{{ category.name }} - Posts {% else %} Posts {% endif %}</h1>
	<div class="row">
		<div class="col-2 offset-1">
			<ul class="nav flex-column">
				<li {% if not category %}class="selected"{% endif %}>
					<p class="h4"><a href="{% url 'post:post_list' %}">All</a></p>
				</li>
				{% for c in categories %}
				<li {% if category.slug == c.slug %}class="selected"{% endif %}>
				<p class="h4"><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></p>

				</li>
				{% endfor %}
			</ul>
		</div>
		<div class="col-9">
			<div class="row">
			{% for post in  page_object.object_list %}

				<div class="card col-3 m-1" style="width: 18rem;">
					<img src="{{ post.image.url }}" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 class="card-title">{{post.title}}</h5>
						<p class="card-text">{{post.body}}</p>

						<p class="card-text">{{post.likes}}</p>
				
								<form action="{% url 'post:like_post_list' post.id %}" method="post">
			<div class="row">
				<div class="col"> 
					<input type="submit" class='btn btn-success' value="Like"></div>
				</div>
				{% csrf_token %}
			</form>
						<a href="{{ post.get_absolute_url }}" class="btn btn-primary">Detail</a>
					</div>
				</div>
			{% endfor %}
			</div>
		</div>
	</div>
	<nav aria-label="..." class='d-flex justify-content-center m-2'>
      <ul class="pagination">
        <li class="page-item {% if  not prev_url%} disabled {% endif %}">
          <a class="page-link" href="{{prev_url}}" tabindex="-1">Previous</a>
        </li>
        {% for n in page_object.paginator.page_range  %}
        {% if page_object.number == n %} 
        <li class="page-item active">
          <a class="page-link" href="?page={{n}}">{{ n }}</a>
        </li>
        {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
        <li class="page-item ">
          <a class="page-link" href="?page={{n}}">{{ n }}</a>
        </li>

        {% endif %}

        {% endfor %}
        <li class="page-item {% if  not next_url%} disabled {% endif %}">
          <a class="page-link" href="{{next_url}}" tabindex="-1">Next</a>
        </li>

      </ul>
    </nav>
{% endblock %}